<?php

declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';

$action = $_REQUEST['action'] ?? '';

// Language switch can use GET and does not need CSRF protection.
if ($action === 'set_language') {
    $lang = $_GET['lang'] ?? 'en';
    $allowed = ['en' => true, 'zh' => true, 'zhs' => true];
    if (isset($allowed[$lang])) {
        $_SESSION['language'] = $lang;
    }
    $redirect = $_SERVER['HTTP_REFERER'] ?? 'index.php';
    header('Location: ' . $redirect);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    exit('Method not allowed');
}

verifyCsrfToken();

$action = $_POST['action'] ?? '';
$isAjax = ($_SERVER['HTTP_X_REQUESTED_WITH'] ?? '') === 'XMLHttpRequest';

function runAndRedirect(callable $callback, string $successMessage, string $errorMessage, string $redirectUrl): never
{
    global $isAjax;
    try {
        $result = $callback();
        $ok = is_array($result) && !empty($result['success']);
        if (!$ok) {
            $detail = is_array($result) && isset($result['output']) && $result['output'] !== ''
                ? $result['output']
                : (is_array($result) ? json_encode($result, JSON_UNESCAPED_SLASHES) : '');
            $message = $detail !== '' ? $errorMessage . "\n\n" . truncateOutput($detail, 1000) : $errorMessage;
            if ($isAjax) {
                jsonResponse(['success' => false, 'error' => $message, 'result' => $result], 500);
            }
            $_SESSION['alert'] = ['type' => 'danger', 'message' => $message];
            header('Location: ' . $redirectUrl);
            exit;
        }
        if ($isAjax) {
            jsonResponse(['success' => true, 'result' => $result]);
        }
        $_SESSION['alert'] = ['type' => 'success', 'message' => $successMessage];
    } catch (Throwable $e) {
        if ($isAjax) {
            jsonResponse(['success' => false, 'error' => $e->getMessage()], 500);
        }
        $_SESSION['alert'] = ['type' => 'danger', 'message' => $e->getMessage()];
    }
    header('Location: ' . $redirectUrl);
    exit;
}

if ($action === 'scan') {
    try {
        $configPath = $_POST['config_path'] ?? $config['default_config_path'] ?? '';
        validateConfigPath((string)$configPath, $config['allowed_config_prefixes']);

        $format = in_array($_POST['format'] ?? '', ['text', 'json', 'csv', 'html'], true)
            ? $_POST['format']
            : ($config['default_report_format'] ?? 'html');
        $dryRun = !empty($_POST['dry_run']);

        set_time_limit($config['max_execution_time']);

        $runner = new FileCleanerRunner(binaryPath($config), $config['max_execution_time']);
        $result = $runner->scan($configPath, $format, $dryRun);

        if ($isAjax) {
            jsonResponse($result);
        }

        // Find the latest JSON report generated by the scan.
        $reports = listReports($config['report_dir']);
        $latestJson = null;
        foreach ($reports as $report) {
            if ($report['type'] === 'json') {
                $latestJson = $report['filename'];
                break;
            }
        }

        $truncated = truncateOutput($result['output'], 2000);
        if ($result['success']) {
            $_SESSION['alert'] = [
                'type' => 'success',
                'message' => __('scan_completed', [
                    'exit_code' => (string)$result['exit_code'],
                    'report' => $latestJson ? $latestJson : '',
                ]),
            ];
        } else {
            $_SESSION['alert'] = [
                'type' => 'danger',
                'message' => __('scan_failed', [
                    'exit_code' => (string)$result['exit_code'],
                ]) . "\n\n" . $truncated,
            ];
        }
    } catch (Throwable $e) {
        if ($isAjax) {
            jsonResponse(['success' => false, 'error' => $e->getMessage()], 500);
        }
        $_SESSION['alert'] = ['type' => 'danger', 'message' => $e->getMessage()];
    }

    header('Location: index.php');
    exit;
}

if ($action === 'approve') {
    $filename = $_POST['report_path'] ?? '';
    $reportPath = $config['report_dir'] . '/' . basename((string)$filename);
    $real = realpath($reportPath);
    if ($real === false || !str_starts_with($real, realpath($config['report_dir']))) {
        $_SESSION['alert'] = ['type' => 'danger', 'message' => __('invalid_report_path')];
        header('Location: reports.php');
        exit;
    }

    runAndRedirect(
        static function () use ($reportPath, $config): array {
            $runner = new FileCleanerRunner(binaryPath($config), $config['max_execution_time']);
            return $runner->approve($reportPath);
        },
        __('report_approved', ['filename' => $filename]),
        __('report_approve_failed', ['filename' => $filename]),
        'reports.php?file=' . urlencode(basename($filename))
    );
}

if ($action === 'apply') {
    $filename = $_POST['report_path'] ?? '';
    $reportPath = $config['report_dir'] . '/' . basename((string)$filename);
    $real = realpath($reportPath);
    if ($real === false || !str_starts_with($real, realpath($config['report_dir']))) {
        $_SESSION['alert'] = ['type' => 'danger', 'message' => __('invalid_report_path')];
        header('Location: reports.php');
        exit;
    }

    runAndRedirect(
        static function () use ($reportPath, $config): array {
            $runner = new FileCleanerRunner(binaryPath($config), $config['max_execution_time']);
            $result = $runner->apply($reportPath, true);
            if (!empty($result['output'])) {
                $result['output'] = truncateOutput($result['output'], 1000);
            }
            return $result;
        },
        __('report_applied', ['filename' => $filename]),
        __('report_apply_failed', ['filename' => $filename]),
        'quarantine.php'
    );
}

if ($action === 'approve_apply') {
    $filename = $_POST['report_path'] ?? '';
    $reportPath = $config['report_dir'] . '/' . basename((string)$filename);
    $real = realpath($reportPath);
    if ($real === false || !str_starts_with($real, realpath($config['report_dir']))) {
        $_SESSION['alert'] = ['type' => 'danger', 'message' => __('invalid_report_path')];
        header('Location: reports.php');
        exit;
    }

    runAndRedirect(
        static function () use ($reportPath, $config, $filename): array {
            $runner = new FileCleanerRunner(binaryPath($config), $config['max_execution_time']);
            $approveResult = $runner->approve($reportPath);
            if (!$approveResult['success']) {
                return $approveResult;
            }
            $applyResult = $runner->apply($reportPath, true);
            if (!empty($applyResult['output'])) {
                $applyResult['output'] = truncateOutput($applyResult['output'], 1000);
            }
            return $applyResult;
        },
        __('report_approved_applied', ['filename' => $filename]),
        __('report_approve_apply_failed', ['filename' => $filename]),
        'quarantine.php'
    );
}

if ($action === 'restore') {
    $filename = $_POST['log_path'] ?? '';
    $logPath = $config['quarantine_dir'] . '/' . $filename;
    $real = realpath($logPath);
    if ($real === false || !str_starts_with($real, realpath($config['quarantine_dir']))) {
        $_SESSION['alert'] = ['type' => 'danger', 'message' => __('invalid_quarantine_log_path')];
        header('Location: quarantine.php');
        exit;
    }

    runAndRedirect(
        static function () use ($logPath, $config, $filename): array {
            $runner = new FileCleanerRunner(binaryPath($config), $config['max_execution_time']);
            $result = $runner->restore($logPath, true);

            // Remove the quarantine log and its empty session directory after a
            // successful restore so the session no longer appears in the listing.
            if (!empty($result['success'])) {
                removeQuarantineSession(dirname($logPath), $config['quarantine_dir']);
            }

            return $result;
        },
        __('files_restored', ['filename' => $filename]),        __('quarantine_restore_failed', ['filename' => $filename]),        'quarantine.php'
    );
}

if ($action === 'purge') {
    $filename = $_POST['log_path'] ?? '';
    $logPath = $config['quarantine_dir'] . '/' . $filename;
    $real = realpath($logPath);
    if ($real === false || !str_starts_with($real, realpath($config['quarantine_dir']))) {
        $_SESSION['alert'] = ['type' => 'danger', 'message' => __('invalid_quarantine_log_path')];
        header('Location: quarantine.php');
        exit;
    }

    runAndRedirect(
        static function () use ($logPath, $config): array {
            removeQuarantineSession(dirname($logPath), $config['quarantine_dir']);
            return ['success' => true];
        },
        __('quarantine_purged', ['session' => basename(dirname($logPath))]),
        __('quarantine_purge_failed', ['session' => basename(dirname($logPath))]),
        'quarantine.php'
    );
}

function truncateOutput(string $output, int $maxLength): string
{
    if (strlen($output) <= $maxLength) {
        return $output;
    }
    return substr($output, 0, $maxLength) . "\n... [output truncated]";
}

function removeQuarantineSession(string $sessionDir, string $quarantineDir): void
{
    if (!is_dir($sessionDir) || realpath($sessionDir) === realpath($quarantineDir)) {
        return;
    }
    if (!str_starts_with(realpath($sessionDir), realpath($quarantineDir))) {
        throw new RuntimeException('Session directory is outside quarantine root');
    }
    $files = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($sessionDir, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($files as $file) {
        $file->isDir() ? rmdir($file->getRealPath()) : unlink($file->getRealPath());
    }
    rmdir($sessionDir);
}

if ($action === 'delete_reports') {
    $files = $_POST['report_files'] ?? [];
    $returnPage = filter_input(INPUT_POST, 'return_page', FILTER_VALIDATE_INT) ?: 1;
    if (!is_array($files) || empty($files)) {
        $_SESSION['alert'] = ['type' => 'warning', 'message' => __('no_reports_selected')];
        header('Location: reports.php?page=' . $returnPage);
        exit;
    }

    runAndRedirect(
        static function () use ($files, $config): array {
            $reportDir = realpath($config['report_dir']);
            if ($reportDir === false) {
                throw new RuntimeException('Report directory is not accessible');
            }

            $deleted = 0;
            $failed = [];
            foreach ($files as $filename) {
                $filename = basename((string)$filename);
                if (!preg_match('/^(report-\d{8}-\d{6})\.(json|html|csv)$/', $filename, $matches)) {
                    $failed[] = "{$filename}: invalid filename";
                    continue;
                }
                $prefix = $matches[1];
                $extensions = ['json', 'html', 'csv'];
                foreach ($extensions as $ext) {
                    $path = $reportDir . '/' . $prefix . '.' . $ext;
                    $real = realpath($path);
                    if ($real === false || !str_starts_with($real, $reportDir)) {
                        continue;
                    }
                    if (unlink($real)) {
                        $deleted++;
                    } else {
                        $failed[] = "{$prefix}.{$ext}: cannot delete";
                    }
                }
            }

            return [
                'success' => empty($failed),
                'deleted' => $deleted,
                'failed' => $failed,
            ];
        },
        __('reports_deleted'),
        __('reports_delete_failed'),
        'reports.php?page=' . $returnPage
    );
}

http_response_code(400);
exit(__('invalid_action'));
